/**
 * 制片国家/地区（ISO 3166-1 alpha-2）
 * 与后端 movies.origin_countries（|US| 形式）及 ?country=US 筛选一致
 */
export const PRODUCTION_COUNTRIES = [
  { code: '', label: '全部国家/地区' },
  { code: 'CN', label: '🇨🇳 中国' },
  { code: 'US', label: '🇺🇸 美国' },
  { code: 'GB', label: '🇬🇧 英国' },
  { code: 'JP', label: '🇯🇵 日本' },
  { code: 'KR', label: '🇰🇷 韩国' },
  { code: 'FR', label: '🇫🇷 法国' },
  { code: 'DE', label: '🇩🇪 德国' },
  { code: 'IN', label: '🇮🇳 印度' },
  { code: 'IT', label: '🇮🇹 意大利' },
  { code: 'ES', label: '🇪🇸 西班牙' },
  { code: 'CA', label: '🇨🇦 加拿大' },
  { code: 'AU', label: '🇦🇺 澳大利亚' },
  { code: 'RU', label: '🇷🇺 俄罗斯' },
  { code: 'BR', label: '🇧🇷 巴西' },
  { code: 'MX', label: '🇲🇽 墨西哥' },
  { code: 'TH', label: '🇹🇭 泰国' },
  { code: 'SG', label: '🇸🇬 新加坡' },
  { code: 'TW', label: '🇹🇼 台湾' },
  { code: 'HK', label: '🇭🇰 香港' },
  { code: 'IE', label: '🇮🇪 爱尔兰' },
  { code: 'NZ', label: '🇳🇿 新西兰' },
  { code: 'SE', label: '🇸🇪 瑞典' },
  { code: 'NO', label: '🇳🇴 挪威' },
  { code: 'DK', label: '🇩🇰 丹麦' },
  { code: 'FI', label: '🇫🇮 芬兰' },
  { code: 'PL', label: '🇵🇱 波兰' },
  { code: 'NL', label: '🇳🇱 荷兰' },
  { code: 'BE', label: '🇧🇪 比利时' },
  { code: 'CH', label: '🇨🇭 瑞士' },
  { code: 'AT', label: '🇦🇹 奥地利' },
  { code: 'AR', label: '🇦🇷 阿根廷' },
  { code: 'TR', label: '🇹🇷 土耳其' },
  { code: 'IL', label: '🇮🇱 以色列' },
  { code: 'ZA', label: '🇿🇦 南非' },
  { code: 'EG', label: '🇪🇬 埃及' },
  { code: 'IR', label: '🇮🇷 伊朗' },
  { code: 'VN', label: '🇻🇳 越南' },
  { code: 'ID', label: '🇮🇩 印度尼西亚' },
  { code: 'PH', label: '🇵🇭 菲律宾' },
  { code: 'MY', label: '🇲🇾 马来西亚' },
];
